version: "3"
      
volumes:
  social-blogging:

services:
  nginx:
    restart: always
    image: nginx:alpine
    volumes:
      - /home/gha/html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/social.caimito.eu:/opt/ssl
    ports:
      - "80:80"
      - "443:443"
  mongo:
    image: mongo
    volumes:
      - social-blogging:/data/db
  social-blogging:
    image: ghcr.io/snscaimito/social-blogging:candidate
    ports:
      - "8080:8080"
    links:
      - mongo
    environment:
      - RSS_FEED=https://host.docker.internal/rss.xml
      - LOGGING_LEVEL_SOCIAL_BLOGGING=WARN
