version: "3"
      
volumes:
  social-blogging:

services:
  nginx:
    profiles:
      - production
    restart: always
    image: nginx:alpine
    volumes:
      - /home/gha/html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/social.caimito.eu:/opt/ssl
    ports:
      - "80:80"
      - "443:443"
  nginx-dev:
    profiles:
      - development
    restart: always
    image: nginx:alpine
    volumes:
      - ../content/_site:/usr/share/nginx/html
      - ./nginx.development.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    links:
      - jekyll
      - social-blogging
  jekyll:
    profiles:
      - development
    image: jekyll/jekyll
    command: jekyll serve --watch --drafts
    volumes:
      - ../content:/srv/jekyll
    ports:
      - 4000:4000
  mongo:
    image: mongo
    volumes:
      - social-blogging:/data/db
  social-blogging:
    image: ghcr.io/snscaimito/social-blogging:candidate
    ports:
      - "8080:8080"
    links:
      - mongo
      - nginx
    environment:
      - RSS_FEED=http://nginx/rss.xml
      - LOGGING_LEVEL_SOCIAL_BLOGGING=DEBUG
      - ATPROTO_HANDLE=stephan-schwab.com
      - ATPROTO_PASSWORD=kypcin-pavgUk-damjo8
      - ATPROTO_PROFILEURL=https://bsky.app/profile/stephan-schwab.com
      - ATPROTO_ENABLED=true
