version: "3"
      
volumes:
  db-data:

services:
  nginx:
    restart: always
    image: nginx:alpine
    volumes:
      - /home/gha/html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/social.caimito.eu:/opt/ssl
    ports:
      - "80:80"
    # links:
      # - social-blogging
  # social-blogging:
  #   links:
  #     - jekyll
  #   build:
  #     context: ../social-blogging
  #   volumes:
  #     - db-data:/var/lib/sqlite
  #   environment:
  #     - RSS_FEED_URL=http://jekyll:4000/rss.xml
