---
- hosts: server
  become: yes
  become_method: sudo

- name: Update host
  ansible.builtin.import_playbook: playbooks/update-host.yml
- name: Install Docker
  ansible.builtin.import_playbook: playbooks/docker.yml
- name: Install DNS
  ansible.builtin.import_playbook: playbooks/dns.yml
