name: Blog Deploy

on:
  push:
    paths:
      - '.github/workflows/main.yml'
      - 'content/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GHA_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  
      - name: SCP files
        run: |
          ssh gha@social.caimito.eu mkdir -p /home/gha/content
          scp -r content gha@social.caimito.eu:/home/gha/

      - name: Start Docker
        run: |
          ssh gha@social.caimito.eu docker-compose up -d

