name: Blog Deploy

on:
  push:
    paths:
      - '.github/workflows/main.yml'
      - 'content/**'
      - 'docker/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GHA_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          ssh-keyscan social.caimito.eu >> ~/.ssh/known_hosts

      - name: Content
        run: |
          ssh gha@social.caimito.eu << 'EOF'
          mkdir -p /home/gha/blog
          if [ -z "\$(ls -A /home/gha/blog)" ]; then
            git clone git@github.com:snscaimito/blog.git /home/gha/blog
          else
            echo "Directory /home/gha/blog is not empty. Skipping clone."
            if [ -d "/home/gha/blog/.git" ]; then
                cd /home/gha/blog && git pull
            else
                echo "/home/gha/blog is not a git repository. Please handle manually."
            fi
          fi
          EOF
        

      - name: Start Docker
        run: |
          ssh gha@social.caimito.eu << 'EOF'
            chmod -R 777 /home/gha/blog/content
            cd /home/gha/blog/docker
            docker compose up -d
          EOF

