name: Blog Deploy

on:
  push:
    paths:
      - '.github/workflows/main.yml'
      - 'content/**'
      - 'docker/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GHA_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          ssh-keyscan social.caimito.eu >> ~/.ssh/known_hosts

      - name: Content
        run: |
          ssh gha@social.caimito.eu << 'EOF'
          if [ -d "/home/gha/blog/.git" ]; then
            cd /home/gha/blog && git pull
          else
            git clone git@github.com:snscaimito/blog.git /home/gha/blog
          fi

          echo "Building the site."
          docker run --volume="$PWD/blog/content:/srv/jekyll" --volume="$PWD/html:/srv/jekyll/_site" jekyll/builder jekyll build _site
          EOF
        

      # - name: Start Docker
      #   run: |
      #     ssh gha@social.caimito.eu << 'EOF'
      #       cd /home/gha/blog/docker
      #       docker compose up -d
      #     EOF

